// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhPGxtakof_kHokFdhpdv35skLodgVReY',
    appId: '1:872425543744:web:c7eaf85b76ed65454d67a5',
    messagingSenderId: '872425543744',
    projectId: 'roomcraft-ai-c4bf7',
    authDomain: 'roomcraft-ai-c4bf7.firebaseapp.com',
    storageBucket: 'roomcraft-ai-c4bf7.firebasestorage.app',
    measurementId: 'G-Q8D23MWR3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOyD0zpYojSnz2EDi0su_YeSyByUIqQTk',
    appId: '1:872425543744:android:7a062bc56ceebd214d67a5',
    messagingSenderId: '872425543744',
    projectId: 'roomcraft-ai-c4bf7',
    storageBucket: 'roomcraft-ai-c4bf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7eM5tb9MeBKlq_mcWlwtYa5VvOpkf4TQ',
    appId: '1:872425543744:ios:2f0d1759a627e9b94d67a5',
    messagingSenderId: '872425543744',
    projectId: 'roomcraft-ai-c4bf7',
    storageBucket: 'roomcraft-ai-c4bf7.firebasestorage.app',
    iosBundleId: 'com.example.roomcraftAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7eM5tb9MeBKlq_mcWlwtYa5VvOpkf4TQ',
    appId: '1:872425543744:ios:2f0d1759a627e9b94d67a5',
    messagingSenderId: '872425543744',
    projectId: 'roomcraft-ai-c4bf7',
    storageBucket: 'roomcraft-ai-c4bf7.firebasestorage.app',
    iosBundleId: 'com.example.roomcraftAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhPGxtakof_kHokFdhpdv35skLodgVReY',
    appId: '1:872425543744:web:842b9bf696a25f024d67a5',
    messagingSenderId: '872425543744',
    projectId: 'roomcraft-ai-c4bf7',
    authDomain: 'roomcraft-ai-c4bf7.firebaseapp.com',
    storageBucket: 'roomcraft-ai-c4bf7.firebasestorage.app',
    measurementId: 'G-EKWS5DG7F9',
  );
}
